github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-dependencies
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-notifications-service-graphql
      branch: 7.0.x
      useSinglePullRequest: true
